#!/bin/bash
#
# Generates a random name similar to the NSA project names

main() {
	local noun
	local adjective

	cd "$(dirname "$0")"/project.d || exit

	noun=$(shuf -n 1 nouns.txt)
	adjective=$(shuf -n 1 adjectives.txt)

	case "$1" in
	"nice")
		adjective=${adjective^}
		noun=${noun^}
		echo "$adjective $noun"
		;;
	*)
		echo "$adjective-$noun"
		;;
	esac
}

main "$@"
