#!/bin/sh

DIR="$(
        cd "$(dirname "$0")"
        pwd
)"

TSKPATH="$HOME"/.cache/tsk
TSKDONE="$TSKPATH"/tasks_done.csv
TSKFILE="$TSKPATH"/tasks.csv
TSKBKP="$TSKFILE".bkp

. "$DIR"/tsk.sh

set -u

main() {
        while true; do
                cp "$TSKFILE" "$TSKBKP"
                sort -t, -k 4 "$TSKBKP" >"$TSKFILE"

                printf 'tsk> ' && read -r args
                # shellcheck disable=SC2086
                set -- $args

                com="$1" && shift
                case "$com" in
                "do")
                        if tskdo "$1"; then
                                tail -n 1 "$TSKDONE"
                        fi
                        ;;
                add)
                        printf 'assignee: ' && read -r assignee
                        printf 'task name: ' && read -r name
                        printf 'category: ' && read -r category
                        printf 'due date: ' && read -r due

                        tskadd "$assignee" "$name" "$category" "$due" "$(date +%y%m%d%H)"
                        ;;
                edit) vi "$TSKFILE" ;;
                exit) exit 0 ;;
                ls) tskls ;;
                *) echo 'tsk: option not recognized' >&2 ;;
                esac
        done
}

main
