#!/bin/sh

set -ue

die(){ echo "E: $*" && exit 1; }

test -z "${1:-}" && die "no arguments given"

subcommand="$1"
shift

case "$subcommand" in
  init)
    mkdir -p current
    mkdir -p .tvc
    ;;

  commit)
    printf "Enter a commit name: "
    read -r name
    name="$(echo "$name" | sed 's/ /-/g')"
    tar -czf ../.tvc/"$name".tar.gz ./*
    echo "Created $name.tar.gz"
    ;;

  checkout)
    test -z "${1:-}" && die "not sure what to checkout"
    printf "Your files: \\n\\t"
    ls -A
    printf "will be lost, do you want to continue? (y/N) "
    read -r response
    test "$response" != "y" && die "Aborted by the user"

    dir="$(mktemp -d)"
    tar -xzf ../.tvc/"$1" -C "$dir"
    rm -rf ./*
    cp "$dir"/*  .
    rm -rf "$dir"
    echo "Checked out successfully."
    ;;

  ls)
    /bin/ls -lrt ../.tvc/
    ;;

  diff)
    /bin/diff ../"$1" ../"$2"
    ;;

  clean)
    for file in ../*; do
      case "$file" in
        *.tvc*) ;;
        *current*) ;;
        *) rm "$file" ;;
      esac
    done
    ;;
  *)
    die "unknown subcommand"
    ;;
esac
