#!/bin/sh

# Programs that will run after Openbox has started

compton -b -c &
connman-gtk &
redshift -l 50:1 &
xfce4-panel &
xfce4-power-manager &
feh --bg-scale /home/cariza/Pictures/9jaq6hz5iib41.png
