#!/bin/sh
#
# Programs that will run after Openbox has started

compton -b -c &
connman-gtk &
feh --bg-scale "$HOME"/Pictures/wallpaper &
redshift -l 50:1 &
xautolock -time 5 -locker slock -detectsleep &
xfce4-panel &
xfce4-power-manager &
